Environments:
  URLs:
  - PreProd: "https://www-ppd.mytoll.com/"
  - Sit: "https://www-ppd.mytoll.com/"
  - Salesforce: "https://test.salesforce.com/"
  - PS: "https://ps.mytoll.com/"

  ActiveEnvironment: "Sit"

  Credentials:
    Usernames:
    - Username1: "SitAutomationuser@mailinator.com"
    - Username2: "auto_bvt_ppd@mailinator.com"
    - SitUsername1: "SitAutomationuser@mailinator.com"
    - SitUsername2: "SitAutomationuser2@mailinator.com"
    - SitUsername3: "SitAutomationuser3@mailinator.com"
    - SitUsername4: "SitAutomationuser4@mailinator.com"
    - SitUsername5: "SitAutomationuser5@mailinator.com"
    - AdminUser: "milarepa@mailinator.com"

    Passwords:
    - Password: "Toll@12345"
    - AdminPassword: "Toll@123"


Browser: "chrome"

Paths:
- chrome: 'bin\chromedriver.exe'
- firefox: 'bin\geckodriver.exe'
- ie: 'bin\IEDriverServer.exe'